wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681907070.990892
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.9.13
      5: 0.14.2
      6: 4.28.1
      8:
      - 1
      - 3
      - 5
      10:
      - 9
